# Generated by Django 4.0.5 on 2022-11-17 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Homemodel',
        ),
    ]
